### ISSUE TITLE
三种 Site 权限

### ISSUE THREAD

**Issue by steedos** [steedos/steedos-cms#17]
![image](https://cloud.githubusercontent.com/assets/3104826/20373230/ca849f62-acab-11e6-8445-eeb09948eae0.png)

![image](https://cloud.githubusercontent.com/assets/3104826/20373838/9beb6420-acaf-11e6-8085-4a99f68983f5.png)

**Comment by yinlianghui** [comment]
![image](https://cloud.githubusercontent.com/assets/6219465/20746935/f5fe4d38-b722-11e6-8d9b-55250ae468e9.png)
现在规则如上图所示。

**Comment by yinlianghui** [comment]
主要变更：

- 移除site的anonymous属性，用visibility代替，可能的值有private/team/public。
- 外网站点有且只有visibility为public才可以查看，其他规则，比如判断当前登录用户权限，全部废除。
- 移除cms中除了site之外所有model的space字段及相关属性，比如categories,post,reads,tags,pages,comments等。
- 所有权限管理重心都转移到site owner/admin，之前有的地方是以space admin为权限重心，全部转换到site中。

**Comment by yinlianghui** [comment]
cms_reads及post.viewCount的逻辑没有因为visibility这个功能增加做任何变更。
