### ISSUE TITLE
每篇文档的下方需要增加点击数

### ISSUE THREAD

**Issue by irenehy** [steedos/steedos-cms#3]
- 数量记录在字段 cms_posts.viewCount ，
- 已阅读人员记录在字段 cms_posts.viewers

- 从发布的外网网站点击文章，viewCount每次+1
- 从cms管理界面点击文章，为避免重复计数，如果当前用户不属于cms_posts.viewers，则viewCount每次+1，并把当前用户加入cms_posts.viewers

**Comment by yinlianghui** [comment]
该功能已完成，cms_posts.viewers字段作废，因为会有性能问题，以一个新表cms_reads代替记录所有阅读历史。
